language: node_js
node_js:
- "14.16.0"
install:
- npm install newman
script:
- node_modules/.bin/newman run tests/TestCollection.json -e tests/NewmanTestEnvironment.json -d tests/DataDrivenInputs.csv
